// ─── Video Category Service ────────────────────────────────────────────────────
// Handles all HTTP requests for the Video Category feature.
// The shared apiClient automatically attaches the Bearer token from localStorage,
// so no manual Authorization header is needed here.

import { apiClient } from "@/lib/api"
import type {
  VideoCategory,
  VideoCategoryListResponse,
  VideoCategoryPayload,
  CategoryListResult,
} from "../types/category.types"

// ── Query params ──────────────────────────────────────────────────────────────

export interface GetVideoCategoriesParams {
  per_page?: number
  search?: string
  page?: number
}

// ── Normalisation helpers ─────────────────────────────────────────────────────

function buildQueryString(params: GetVideoCategoriesParams): string {
  const qs = new URLSearchParams()
  if (params.per_page !== undefined) qs.set("per_page", String(params.per_page))
  if (params.search) qs.set("search", params.search)
  if (params.page !== undefined && params.page > 1) qs.set("page", String(params.page))
  const str = qs.toString()
  return str ? `?${str}` : ""
}

// ── API functions ─────────────────────────────────────────────────────────────

/**
 * Fetch video categories with optional search / pagination.
 * Endpoint: GET /admin/video-categories/getAll
 */
export async function getVideoCategories(
  params: GetVideoCategoriesParams = {},
): Promise<CategoryListResult> {
  const qs = buildQueryString(params)
  const response = await apiClient.get<VideoCategoryListResponse>(
    `/admin/video-categories/getAll${qs}`,
  )

  const items: VideoCategory[] = Array.isArray(response?.data) ? response.data : []
  const cards = Array.isArray(response?.cards) ? response.cards : []
  const meta = response?.meta ?? null

  return { items, cards, meta }
}

/**
 * Fetch a single video category by ID.
 * Endpoint: GET /admin/video-categories/getById/{id}
 */
export async function getVideoCategoryById(id: number): Promise<VideoCategory> {
  const response = await apiClient.get<{ data: VideoCategory }>(
    `/admin/video-categories/getById/${id}`,
  )
  return response.data
}

/**
 * Create a new video category.
 * Endpoint: POST /admin/video-categories/create
 *
 * Returns the newly created VideoCategory (HTTP 201).
 * The slug is auto-generated by the backend — do not include it in the payload.
 */
export async function createVideoCategory(
  payload: VideoCategoryPayload,
): Promise<VideoCategory> {
  const response = await apiClient.post<{ data: VideoCategory }>(
    "/admin/video-categories/create",
    payload,
  )
  // Backend wraps the created resource in a `data` envelope
  return response?.data ?? (response as unknown as VideoCategory)
}

/**
 * Update an existing video category by its ID.
 * Endpoint: PUT /admin/video-categories/update/{id}
 *
 * Returns the updated VideoCategory (HTTP 200).
 * The slug is updated automatically when the name changes.
 */
export async function updateVideoCategory(
  id: number,
  payload: VideoCategoryPayload,
): Promise<VideoCategory> {
  const response = await apiClient.put<{ data: VideoCategory }>(
    `/admin/video-categories/update/${id}`,
    payload,
  )
  return response?.data ?? (response as unknown as VideoCategory)
}

/**
 * Delete a video category by its ID.
 * Endpoint: DELETE /admin/video-categories/delete/{id}
 *
 * Returns void on success (HTTP 200).
 * Throws an ApiError with status 422 if the category has linked videos.
 */
export async function deleteVideoCategory(id: number): Promise<void> {
  return apiClient.delete<void>(`/admin/video-categories/delete/${id}`)
}
